### ISSUE TITLE
curl https://jobber.gisadan.dev/api/export/sqlite require user/pass, can you share a small size database here? thank you

### ISSUE THREAD

**Issue by techhubhub** [LiteralGenie/jobber-classifier#2]
curl https://jobber.gisadan.dev/api/export/sqlite require user/pass, can you share a small size database here? thank you

**Comment by LiteralGenie** [comment]
Sorry that's the wrong url, it should be https://jobber.velchees.dev/api/export/sqlite
(If that doesn't work, here's a ~5MB zip: [db.sqlite.zip](https://github.com/LiteralGenie/jobber-classifier/files/14485830/db.sqlite.zip) )

I've also fixed the readme, sorry about that!
